### ISSUE TITLE
Missing content in Device Whitelisting

### ISSUE THREAD

**Issue by michalzobec** [nsacyber/Windows-Secure-Host-Baseline#55]
Hello,

thank you for your great project. I found directory "Device Whitelisting" but is without any useful information. Can you update it? :)

Thank you.
Michal

**Comment by iadgovuser1** [comment]
I thought we had removed this a while back. Guess not. The device whitelisting folder was going to have [Device Installation Restriction](https://msdn.microsoft.com/en-us/library/bb530324.aspx) GPOs that implement the whitelisting policies. That never became part of the SHB because it is only useful in certain situations.

This repo has a mix of SHB and non-SHB stuff (like BitLocker and ActivClient). Good chance we will archive this repository because there hasn't been much demand. If the repo survives it will be in greatly stripped down form.
